name: Take meteo snapshot

on:
  schedule:
    - cron: '17 3 * * *'

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      run: pipx install poetry
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        cache: "poetry"
    - name: Install dependencies
      run: |
        poetry install
    - name: Fetch today's data
      run: |
        mkdir -p data
        python etl.py
    - name: Commit new data & push
      run: |-
        git config user.name "Automated"
        git config user.name "actions@users.noreply.github.com"
        git add data/
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
